# Generated by Django 4.2.4 on 2023-11-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('finance', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.CharField(choices=[('KIRISH', 'KIRISH'), ('CHIQISH', 'CHIQISH'), ('OYLIK_TULOV', 'OYLIK_TULOV')], max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sended_date', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.student')),
                ('debts', models.ManyToManyField(blank=True, related_name='messages', to='finance.student_debt')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.parent')),
            ],
        ),
    ]
